[tasks.fmt]
description = "Format TOML files"
run = "taplo format"

[tasks.clean]
description = "Clean cache files"
run = "rm -rf ~/.cache/zsh_* */**.zwc ./*.zwc"

[tools]
shellcheck = "latest"
shfmt = "latest"
taplo = "latest"

[settings]
experimental = true
