# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

[plugins.autocomplete]
github = "marlonrichert/zsh-autocomplete"
use = ["zsh-autocomplete.plugin.zsh"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
use = ["{{ name }}.zsh"]

[plugins.yous-should-use]
github = "MichaelAquilina/zsh-you-should-use"
use = ["you-should-use.plugin.zsh"]

[plugins.shell-logger]
github = "rcmdnk/shell-logger"
use = ["etc/shell-logger"]


[plugins.brew]
github = "ohmyzsh/ohmyzsh"
profiles = ["Darwin"]
use = ["plugins/brew/brew.plugin.zsh"]

[plugins.custom-plugins]
local = "~/dotfiles/custom/"
use = ["*.zsh"]
